import 'dart:convert';
import 'package:flutter/material.dart';
// ⚠️ USER: Added custom imports
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// Auto-generated comprehensive example
/// Generated by code generator v1.0
/// ⚠️ USER: Modified documentation
/// Custom notes: This class has been enhanced with validation

// Type definitions
typedef JsonMap = Map<String, dynamic>;
// ⚠️ USER: Added custom typedef
typedef TaskList = List<Task>;
typedef ValidationCallback = bool Function(String);

// Top-level constants
const String apiVersion = 'v1';
const int defaultTimeout = 30;
// ⚠️ USER: Added custom constants
const int maxRetries = 3;
const bool enableDebugMode = true;

// ⚠️ USER: Added custom top-level variable
final dateFormatter = DateFormat('dd/MM/yyyy HH:mm');

// Enums
enum Status {
  pending,
  active,
  completed,
  cancelled
}

enum Priority {
  low,
  medium,
  high
}

// ⚠️ USER: Added custom enum
enum TaskType {
  personal,
  work,
  urgent
}

// Top-level function
String formatResponse(dynamic data) {
  return json.encode(data);
}

// ⚠️ USER: Added custom top-level function
/// Validates if a string is not empty
bool validateNotEmpty(String? value) {
  return value != null && value.trim().isNotEmpty;
}

// ⚠️ USER: Added custom function with complex logic
DateTime? parseCustomDate(String? dateStr) {
  if (dateStr == null) return null;
  try {
    return DateFormat('dd/MM/yyyy').parse(dateStr);
  } catch (e) {
    return null;
  }
}

/// Main data model
class Task {
  Task({
    this.id,
    required this.title,
    this.description,
    this.status,
    this.priority,
    // ⚠️ USER: Added custom fields
    this.createdAt,
    this.updatedAt,
    this.assignedTo,
    this.tags,
  });

  int? id;
  String title;
  String? description;
  Status? status;
  Priority? priority;

  // ⚠️ USER: Added custom fields
  DateTime? createdAt;
  DateTime? updatedAt;
  String? assignedTo;
  List<String>? tags;

  // ⚠️ USER: Added custom getter
  bool get isOverdue {
    if (updatedAt == null) return false;
    return DateTime.now().difference(updatedAt!).inDays > 7;
  }

  // ⚠️ USER: Added custom method
  void markAsCompleted() {
    status = Status.completed;
    updatedAt = DateTime.now();
  }

  // ⚠️ USER: Added custom validation
  bool validate() {
    return validateNotEmpty(title) && title.length >= 3;
  }

  bool validateTaylson() {
    return validateNotEmpty(title) && title.length >= 3;
  }

  // ⚠️ USER: Override equality operator
  @override
  bool operator ==(Object other) =>
      identical(this, other) || other is Task && id == other.id;

  @override
  int get hashCode => id.hashCode;

  factory Task.fromJson(JsonMap json) => Task(
        id: json['id'] as int?,
        title: json['title'] as String,
        description: json['description'] as String?,
        status: json['status'] != null
            ? Status.values.firstWhere((e) => e.name == json['status'])
            : null,
        priority: json['priority'] != null
            ? Priority.values.firstWhere((e) => e.name == json['priority'])
            : null,
        // ⚠️ USER: Added custom field parsing
        createdAt: json['createdAt'] != null
            ? DateTime.parse(json['createdAt'] as String)
            : null,
        updatedAt: json['updatedAt'] != null
            ? DateTime.parse(json['updatedAt'] as String)
            : null,
        assignedTo: json['assignedTo'] as String?,
        tags: (json['tags'] as List<dynamic>?)?.cast<String>(),
      );

  JsonMap toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'status': status?.name,
        'priority': priority?.name,
        // ⚠️ USER: Added custom fields to JSON
        'createdAt': createdAt?.toIso8601String(),
        'updatedAt': updatedAt?.toIso8601String(),
        'assignedTo': assignedTo,
        'tags': tags,
      };
}

// Service class
class TaskService {
  final String baseUrl;

  // ⚠️ USER: Added custom field
  late SharedPreferences _prefs;
  final int maxRetries;

  // ⚠️ USER: Modified constructor
  TaskService(this.baseUrl, {this.maxRetries = 3});

  // ⚠️ USER: Added custom initialization method
  Future<void> init() async {
    _prefs = await SharedPreferences.getInstance();
  }

  Future<List<Task>> fetchTasks() async {
    // Generated implementation
    throw UnimplementedError();
  }

  Future<Task> createTask(Task task) async {
    // Generated implementation
    throw UnimplementedError();
  }

  // ⚠️ USER: Added custom methods
  Future<void> saveTaskLocally(Task task) async {
    final tasks = await getLocalTasks();
    tasks.add(task);
    await _prefs.setString('tasks', json.encode(tasks.map((t) => t.toJson()).toList()));
  }

  Future<List<Task>> getLocalTasks() async {
    final tasksJson = _prefs.getString('tasks');
    if (tasksJson == null) return [];
    final list = json.decode(tasksJson) as List<dynamic>;
    return list.map((e) => Task.fromJson(e as JsonMap)).toList();
  }

  // ⚠️ USER: Added retry logic
  Future<Task> createTaskWithRetry(Task task) async {
    for (int i = 0; i < maxRetries; i++) {
      try {
        return await createTask(task);
      } catch (e) {
        if (i == maxRetries - 1) rethrow;
        await Future.delayed(Duration(seconds: 2 * (i + 1)));
      }
    }
    throw Exception('Failed after $maxRetries retries');
  }
}

// Extension
extension TaskExtension on Task {
  bool get isCompleted => status == Status.completed;

  // ⚠️ USER: Added custom extension methods
  bool get isPending => status == Status.pending;

  String get statusLabel {
    switch (status) {
      case Status.pending:
        return 'Pendente';
      case Status.active:
        return 'Ativo';
      case Status.completed:
        return 'Concluído';
      case Status.cancelled:
        return 'Cancelado';
      default:
        return 'Desconhecido';
    }
  }

  Color get priorityColor {
    switch (priority) {
      case Priority.high:
        return Colors.red;
      case Priority.medium:
        return Colors.orange;
      case Priority.low:
        return Colors.green;
      default:
        return Colors.grey;
    }
  }
}

// ⚠️ USER: Added new extension
extension StringExtension on String {
  bool get isValidTitle => trim().length >= 3 && trim().length <= 100;
}

// ⚠️ USER: Added custom utility class
class TaskValidator {
  static bool isValid(Task task) {
    return task.title.isValidTitle;
  }

  static String? validateTitle(String? title) {
    if (title == null || title.isEmpty) {
      return 'Título é obrigatório';
    }
    if (title.length < 3) {
      return 'Título deve ter no mínimo 3 caracteres';
    }
    return null;
  }
}

