import 'dart:convert';
import 'package:flutter/material.dart';

/// Auto-generated comprehensive example
/// Generated by code generator v1.0

// Type definitions
typedef JsonMap = Map<String, dynamic>;

// Top-level constants
const String apiVersion = 'v1';
const int defaultTimeout = 30;

// Enums
enum Status {
  pending,
  active,
  completed,
  cancelled
}

enum Priority {
  low,
  medium,
  high
}

// Top-level function
String formatResponse(dynamic data) {
  return json.encode(data);
}

/// Main data model
class Task {
  Task({
    this.id,
    required this.title,
    this.description,
    this.status,
    this.priority,
  });

  int? id;
  String title;
  String? description;
  Status? status;
  Priority? priority;

  factory Task.fromJson(JsonMap json) => Task(
        id: json['id'] as int?,
        title: json['title'] as String,
        description: json['description'] as String?,
        status: json['status'] != null
            ? Status.values.firstWhere((e) => e.name == json['status'])
            : null,
        priority: json['priority'] != null
            ? Priority.values.firstWhere((e) => e.name == json['priority'])
            : null,
      );

  JsonMap toJson() => {
        'id': id,
        'title': title,
        'description': description,
        'status': status?.name,
        'priority': priority?.name,
      };
}

// Service class
class TaskService {
  final String baseUrl;

  TaskService(this.baseUrl);

  Future<List<Task>> fetchTasks() async {
    // Generated implementation
    throw UnimplementedError();
  }

  Future<Task> createTask(Task task) async {
    // Generated implementation
    throw UnimplementedError();
  }
}

// Extension
extension TaskExtension on Task {
  bool get isCompleted => status == Status.completed;
}

